$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$npm = 'C:\Program Files\nodejs\npm.cmd'
$npx = 'C:\Program Files\nodejs\npx.cmd'
if (-not (Test-Path $npm)) {
  throw 'npm not found at C:\Program Files\nodejs\npm.cmd'
}

$env:Path = 'C:\Program Files\nodejs;' + $env:Path
Remove-Item Env:ELECTRON_RUN_AS_NODE -ErrorAction SilentlyContinue

$runtimeDir = Join-Path $root 'build\desktop-runtime'
$backendRuntime = Join-Path $runtimeDir 'backend'
$webRuntime = Join-Path $runtimeDir 'web-runtime'

if (Test-Path $runtimeDir) {
  Remove-Item $runtimeDir -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $backendRuntime | Out-Null
New-Item -ItemType Directory -Force -Path $webRuntime | Out-Null

Write-Host '[1/4] Build backend exe...' -ForegroundColor Cyan
python -m pip install pyinstaller
python -m PyInstaller --noconfirm --onefile --name PokemonRP-Backend --distpath "$backendRuntime" --workpath "$root\build\pyi-work" --specpath "$root\build\pyi-spec" scripts/backend_entry.py

Write-Host '[2/4] Build frontend production assets...' -ForegroundColor Cyan
Push-Location "$root\web"
try {
  & $npm install
  & $npm run build
}
finally {
  Pop-Location
}

Write-Host '[3/4] Prepare frontend runtime files...' -ForegroundColor Cyan
$webSource = Join-Path $root 'web'
$standaloneSource = Join-Path $webSource '.next\standalone'
$staticSource = Join-Path $webSource '.next\static'
if (-not (Test-Path $standaloneSource)) {
  throw "Next standalone build output missing: $standaloneSource"
}
if (-not (Test-Path $staticSource)) {
  throw "Next static build output missing: $staticSource"
}

# Copy minimal runtime generated by Next standalone mode.
Copy-Item (Join-Path $standaloneSource '*') -Destination $webRuntime -Recurse -Force

$staticTarget = Join-Path $webRuntime '.next\static'
New-Item -ItemType Directory -Force -Path $staticTarget | Out-Null
Copy-Item (Join-Path $staticSource '*') -Destination $staticTarget -Recurse -Force

$publicSource = Join-Path $webSource 'public'
if (Test-Path $publicSource) {
  Copy-Item $publicSource -Destination (Join-Path $webRuntime 'public') -Recurse -Force
}

$cacheTarget = Join-Path $webRuntime '.next\cache'
if (Test-Path $cacheTarget) {
  Remove-Item $cacheTarget -Recurse -Force
}

Write-Host '[4/4] Package Electron desktop (Windows x64)...' -ForegroundColor Cyan
Push-Location "$root\desktop"
try {
  & $npm install
  & $npm install --save-dev electron-packager
  & $npx electron-packager . PokemonRP-Desktop --platform=win32 --arch=x64 --out="$root\dist" --overwrite --extra-resource "$backendRuntime" --extra-resource "$webRuntime"
}
finally {
  Pop-Location
}

Write-Host ''
Write-Host "Build done: $root\dist\PokemonRP-Desktop-win32-x64\PokemonRP-Desktop.exe" -ForegroundColor Green
Write-Host "Runtime includes backend exe + frontend build. Target PC does not need Python/Node." -ForegroundColor Green
